// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5VsgMV1HW_F9RCFBc8lgYIIOH8rPxPf0',
    appId: '1:368515858457:web:4b761971e52e08dfdeea88',
    messagingSenderId: '368515858457',
    projectId: 'ingenious-5',
    authDomain: 'ingenious-5.firebaseapp.com',
    storageBucket: 'ingenious-5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgVr9rBisHgIFgO5VSaVlBf5JhSR4rZNw',
    appId: '1:368515858457:android:f33688440d558736deea88',
    messagingSenderId: '368515858457',
    projectId: 'ingenious-5',
    storageBucket: 'ingenious-5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSaGCcpb-oB26zzEA1tz2lSWA34crtFnw',
    appId: '1:368515858457:ios:c30ca20ee64e6a3bdeea88',
    messagingSenderId: '368515858457',
    projectId: 'ingenious-5',
    storageBucket: 'ingenious-5.appspot.com',
    iosBundleId: 'com.example.ingenious5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSaGCcpb-oB26zzEA1tz2lSWA34crtFnw',
    appId: '1:368515858457:ios:4069e372fdecc119deea88',
    messagingSenderId: '368515858457',
    projectId: 'ingenious-5',
    storageBucket: 'ingenious-5.appspot.com',
    iosBundleId: 'com.example.ingenious5.RunnerTests',
  );
}
